apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: diskplugin.csi.alibabacloud.com
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  seLinuxMount: true
  volumeLifecycleModes:
    - Persistent
